services:
  dev-db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nusc
    networks:
      - nusc
    volumes:
      - nusc-backend-db:/var/lib/postgresql/data
networks:
  nusc:
volumes:
  nusc-backend-db:
